version: '3.8'

services:
  springboot_api:
    image: 'docker-spring-boot-postgres'
    container_name: "springboot_backend"
    build:
      context: .
      dockerfile: ./api/DOCKERFILE
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresdatabase:5432/todolist_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    depends_on:
      postgresdatabase:
        condition: service_healthy
    networks: 
      - backend
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health | grep UP || exit 1"
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s

  postgresdatabase:
    image: postgres:16
    container_name: "postgresDB"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todolist_db
    networks: 
      - backend
    volumes:
        - './.containers/data:/var/lib/postgresql/data'
    ports: 
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]
      interval: 1s
      timeout: 5s
      retries: 5
      start_period: 20s

networks:
  backend: 
    name: backend_bridge_network
    driver: bridge

volumes:
  postgres_data:
    driver: local