openapi: 3.0.0
info:
  title: (title)
  version: 0.0.0
tags: []
paths:
  /task/v2:
    get:
      operationId: Tasks_list
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
components:
  schemas:
    Task:
      type: object
      required:
        - id
        - title
        - description
        - completed
        - createdAt
        - updatedAt
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        completed:
          type: boolean
        createdAt:
          type: string
        updatedAt:
          type: string
