logging:
  file:
    name: logs/myapp.log
  level:
    root: ERROR
    org.springframework: INFO
    org.springframework.jdbc.datasource: ERROR
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

spring:
  application:
    name: springboot
  jackson:
    property-naming-strategy: SNAKE_CASE
  flyway:
    locations: classpath:/db/migration
    schemas: tasks
    baselineOnMigrate: true
    enabled: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8081 # HTTPS port
  ssl:
    key-store: keystore.pfx  # Path to your keystore file
    key-store-password: logintest  # Password used to protect the keystore
    key-store-type: PKCS12  # Type of keystore, in this case, PKCS12
    key-alias: testingKey  # Alias of the key within the keystore
    enabled: true  # Enable SSL/TLS

auth:
  app:
    jwtSecret: testStringtestStringtestStringtestStringtestStringtestStringtestStringtestStringtestStringtestString
    jwtExpirationMs: 86400000